# Example hackazon in yaml

# To run:
#   kubectl apply -f pod.yaml
#command ot expose service  kc expose pod  hackazon-with-sidecar --type=NodePort --port=80 --target-port=81 
#curl http://clusterip

apiVersion: v1
kind: Pod
metadata:
  name: hackazon-with-sidecar
  labels:
    app: hackazon-with-sidecar
spec:
  # In the sidecar pattern, there is a main application
  # container and a sidecar container.
  containers:

  # Main application container
  - name: hackazon-container
    # Simple application: write the current date
    # to the log file every five seconds
    image: ianwijaya/hackazon # alpine is a simple Linux OS image

  # Sidecar container
  - name: nginx-container
    # Simple sidecar: display log files using nginx.
    # In reality, this sidecar would be a custom image
    # that uploads logs to a third-party or storage service.
    image: nginx:1.7.9
    ports:
      - containerPort: 81

    # Mount the pod's shared log file into the sidecar
    # container. In this case, nginx will serve the files
    # in this directory.
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf 
  volumes:
  -  name: nginx-proxy-config
     configMap:
       name: nginx-conf    
